---
title: "Collection of Free online Materials"
date: 2020-05-01
description: ""
tags: []
---

**Collection of online links that I find useful and I need to remember**

Though bookmarks work well for browsers but hey I cannot share that to others.

**Caveat**    : Limited to my interest and frequent reads

**Disclaimer**: Not promotional or marketing of any sorts


## R Online Books

* [R for Data Science](https://r4ds.had.co.nz/) 
* [Happy Git with R](https://happygitwithr.com/)
* [Advanced R](https://adv-r.hadley.nz/)
* [Mastering Shiny](https://mastering-shiny.org/) though still under review
* [Blog using R](https://bookdown.org/yihui/blogdown/) once you start road of down, I would advice starting with the [RMarkdown](https://bookdown.org/yihui/rmarkdown) which will take you down the rabbit hole to [Bookdown](https://bookdown.org/yihui/bookdown/)
* [R Cookbook](https://rc2e.com/)
* [R Graphics Cookbook](https://r-graphics.org/)

## Python Online Books

* [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/)


## Command line Online Books

* [Data Science at the Command Line](https://www.datascienceatthecommandline.com/index.html)


## Other content/Interesting blog online

* Learn R and Python in Parallel [Another Book on Data Science](https://www.anotherbookondatascience.com/) though still under review
* Excel VBA Blog tutorials [Excel VBA](https://excelmacromastery.com/vba-articles/)

* SPSS syntax tutorials on steroids, including R and Python scripts [Raynald's SPSS Tools](http://www.spsstools.net/en/)
* Java script for data science using npm [Java for DS](http://js4ds.org/)
* Data Visualization tips [dataviz](https://serialmentor.com/dataviz/balance-data-context.html)

* STATA/R/SPSS code examples [EconometricsbySimulation](http://www.econometricsbysimulation.com/)

* Most of the above R especially resources can be searched and gotten under the list of bookdown books [here](https://bookdown.org/)