---
title: "Beauty of Language"
date: 2019-12-10T02:01:58+05:30
description: "Under the tree scenarios play a lot in my mind, questioning and marveling at the interesting facets and crevices of the world."
tags: ["Random","Language"]
---


# **BEAUTY OF LANGUAGE**

-------------------------

Under the tree scenarios play a lot in my mind, questioning and marveling at the interesting facets and crevices of the world. The complex nature of which we find ourselves in, dynamism, mystism, elusions and perfections all sewn into one. One would be forgiven for not appreciating all the asthetics that come from the universe.


Communication is at the core of human societies, cultures and being. The constant longing for expression of self to the universe, seeking attention or addressing a need. These various forms of expressions are intriging not to say the least my main focus is on language.
Language, intonation of various sounds to produce letters forming words ultimately sentences. Further creating a web of conversation. We are able to store human memories through language being able to share experiences from one generation to another, moving from truths to stories to myths.


Queries always linger in my mind, on how homo sapiens have evolved to such an extent as communicating with such a form, language. Approximate figures place the number of languges in the world at [6500](https://www.infoplease.com/askeds/how-many-spoken-languages), this are not fully unique languages as majority hold a resemblance or share certain words. That aside the marvel of having all this language and still beig able to direct, guide and share is nothing short of glorious.


These has led me to ask, what are the origin of langauge. Pardon me for my naivity, I will excuse myself am not a linguist neigther an anthoropolgist, I lack any history background. Most of what I think are my own casual inference based on the limited knowledge I have thus far. 
As far as I am concerned we do not have any trace or origin of language, no ground zero start point of language. It is almost synonymous to human nature we just start talking at some point as part of growth, probably would relate to how certain animals pick up walking on all fours in less than hours time from birth. Do get me correctly I have just said talk not really make sense, the sense part of communication comes up way later. We pick up speech from our environment, the different conversation we start hearing. The more we call a baby mum or dad the first word they will utter will be either of the two. Here is now where conversation starts.


Part of the human psyche is being able to process the reverberation of vocal codes to make understanding of speech. That meant at some point there has to be an agreement on the structure and sequence of this revibration to be able to conclude what we are communicating.
I have not been able to trace the start of verbal structural communication as we know it, this seems to have developed as some of our other senses i.e. sight, smell, touch and hearing. 


From one of the religious group we note that language was universal with only one similar language, till the this was broken down to different languages, thus in one day we went from one language to multiple diverse language.


Scientifically or rather historically as homo species continued to explore the world from the known world at the time, languages continued to evolve too differently due to change of environment and discovery of new materials, flora and fauna. Imagine moving from the center of the continent which is landlock to moving to the end of the continent where you meet the ocean for the first time. You will name the ocean or give it some sort of descriptive word. Thus morphologizing of languages, this though does not account for the distinctness of languages, where no single word is common or even meaning. Listening to people speak languages I cannot understand fathoms me at how we has humans are very intricate, complex and at bear minimum complicated. The interplay of words, accent and pronunciation from the click of Nkosa in South of Africa to the whistles of Silbo Gomero languge in the coast of spain.


Interestingly language like life is not infinite it is finite, with historical material mentioning that some of languages are extinct and others are new languages, other languages are old language which have survived the times. Other languages are still taught and spoken but not actively used for example Latin. Forgive me if am limited in scope interms of all languages spoken and the emerging or disappearance of language. 


One thing for sure is converging of languages which is being experienced, it is as if we at some point are working towards one common universal language, the new langauge will have interesting facets inclusion of pictorial representation some already have names Emojis :). Which ever that language will be we have already translated most commonly spoken languages to other commonly spoken languages. With the emergence of natural language processing then this translation will continue further as word translation has happened the next frontier will be sentence structure translation.
